name: Build and Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          rustflags: '' # Prevents extraneous warnings and extra flags on CI (this is not necessarly a good idea or permanent so please don't always expect warnings to be ignored)
      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}


      - name: Build
        run: cargo build --verbose

      - name: Run tests
        timeout-minutes: 5 # if tests take longer than 5 minutes, they are likely to be hung so fail the build
        run: cargo test
